/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksBackfillForecastsRouteImport } from './routes/api/public/hooks/backfill-forecasts'
import { Route as ApiPublicHooksDailyForecastRouteImport } from './routes/api/public/hooks/daily-forecast'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBackfillForecastsRoute =
  ApiPublicHooksBackfillForecastsRouteImport.update({
    id: '/api/public/hooks/backfill-forecasts',
    path: '/api/public/hooks/backfill-forecasts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyForecastRoute =
  ApiPublicHooksDailyForecastRouteImport.update({
    id: '/api/public/hooks/daily-forecast',
    path: '/api/public/hooks/daily-forecast',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/hooks/backfill-forecasts': typeof ApiPublicHooksBackfillForecastsRoute
  '/api/public/hooks/daily-forecast': typeof ApiPublicHooksDailyForecastRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/hooks/backfill-forecasts': typeof ApiPublicHooksBackfillForecastsRoute
  '/api/public/hooks/daily-forecast': typeof ApiPublicHooksDailyForecastRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/hooks/backfill-forecasts': typeof ApiPublicHooksBackfillForecastsRoute
  '/api/public/hooks/daily-forecast': typeof ApiPublicHooksDailyForecastRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/hooks/backfill-forecasts'
    | '/api/public/hooks/daily-forecast'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/hooks/backfill-forecasts'
    | '/api/public/hooks/daily-forecast'
  id:
    | '__root__'
    | '/'
    | '/api/public/hooks/backfill-forecasts'
    | '/api/public/hooks/daily-forecast'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHooksBackfillForecastsRoute: typeof ApiPublicHooksBackfillForecastsRoute
  ApiPublicHooksDailyForecastRoute: typeof ApiPublicHooksDailyForecastRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-forecasts': {
      id: '/api/public/hooks/backfill-forecasts'
      path: '/api/public/hooks/backfill-forecasts'
      fullPath: '/api/public/hooks/backfill-forecasts'
      preLoaderRoute: typeof ApiPublicHooksBackfillForecastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-forecast': {
      id: '/api/public/hooks/daily-forecast'
      path: '/api/public/hooks/daily-forecast'
      fullPath: '/api/public/hooks/daily-forecast'
      preLoaderRoute: typeof ApiPublicHooksDailyForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHooksBackfillForecastsRoute: ApiPublicHooksBackfillForecastsRoute,
  ApiPublicHooksDailyForecastRoute: ApiPublicHooksDailyForecastRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
